Revert "Fix syntax error in catch.hpp".  This was breaking gcc 9.2.0 and gcc 5.4.0
This reverts commit 861274813aebc16b5277fa24ef630fb19aceca7b.

In file included from /home/heafield/intgemm/test/test.h:3:0,
                 from /home/heafield/intgemm/test/test.cc:2:
/home/heafield/intgemm/test/../3rd_party/catch.hpp:7732:10: error: prototype for ‘Catch::clara::detail::Parser Catch::clara::detail::ComposableParserImpl<DerivedT>::operator|(const T&) const’ does not match any in class ‘Catch::clara::detail::ComposableParserImpl<DerivedT>’
     auto ComposableParserImpl<DerivedT>::operator|( T const &other ) const -> Parser {
          ^
/home/heafield/intgemm/test/../3rd_party/catch.hpp:7325:14: error: candidate is: template<class DerivedT> template<class T> Catch::clara::detail::Parser Catch::clara::detail::ComposableParserImpl<DerivedT>::operator|(const T&) const
         auto operator|( T const &other ) const -> Parser;
              ^